services:
  node1:
    build:
      context: .
      dockerfile: node/Dockerfile
    image: kv-node
    ports:
      - "7001:7001"
      - "9010:9010"
    depends_on:
      - router
    environment:
      JMX_HOST: localhost
      NODE_ADDRESS: node1
      KV_ROUTER_URL: http://router:6999
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g

  node2:
    image: kv-node
    ports:
      - "7002:7001"
    depends_on:
      - router
    environment:
      NODE_ADDRESS: node2
      KV_ROUTER_URL: http://router:6999
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g

  node3:
    image: kv-node
    ports:
      - "7003:7001"
    depends_on:
      - router
    environment:
      NODE_ADDRESS: node3
      KV_ROUTER_URL: http://router:6999
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g

  router:
    build:
      context: .
      dockerfile: router/Dockerfile
    image: kv-router
    ports:
      - "6999:6999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
