spring.application.name=kv
spring.threads.virtual.enabled=true
server.port=7001

kv.data-store-type=locking
kv.router-url=http://localhost:6999
kv.heartbeat-interval-ms=15000

logging.level.jirat.viriyataranon=WARN