spring.application.name=router
server.port=6999

router.eviction-threshold-ms=60000
router.eviction-check-interval-ms=15000
router.http-connect-timeout-ms=2000
router.http-read-timeout-ms=10000

logging.level.jirat.viriyataranon=INFO
